@startuml
' A "library" file split into named sub-blocks with !startsub / !endsub.
' Other diagrams pull individual sections via  !includesub example$roles.puml!<Name>.

!startsub Core
!include example$layout/colors.puml
abstract class Party
class Individual extends Party
class Organization extends Party
!endsub

!startsub Roles
class PartyRole
class Customer extends PartyRole
class Supplier extends PartyRole
Party "1" -- "*" PartyRole
!endsub
@enduml
